

services:
  app-service:
    image: app-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-service
    ports:
      - "8000:8000"

  postgres-service:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql_script/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

volumes:
  db-data: